"""Add tiebreaker fields

Revision ID: 2891de635c8f
Revises: 75e96c5a6026
Create Date: 2025-12-20 00:29:26.128579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2891de635c8f'
down_revision = '75e96c5a6026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('soty_matchups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_tied', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('tie_resolved_by_admin', sa.Boolean(), nullable=True))

    with op.batch_alter_table('soty_rounds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tiebreaker_end_date', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('soty_rounds', schema=None) as batch_op:
        batch_op.drop_column('tiebreaker_end_date')

    with op.batch_alter_table('soty_matchups', schema=None) as batch_op:
        batch_op.drop_column('tie_resolved_by_admin')
        batch_op.drop_column('is_tied')

    # ### end Alembic commands ###
