"""Initial migration with plant models

Revision ID: 635abf4f1200
Revises: 
Create Date: 2025-12-14 13:00:31.823531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '635abf4f1200'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('common_name', sa.String(length=100), nullable=False),
    sa.Column('scientific_name', sa.String(length=150), nullable=True),
    sa.Column('plant_type', sa.String(length=50), nullable=True),
    sa.Column('native_region', sa.String(length=100), nullable=True),
    sa.Column('height_range', sa.String(length=50), nullable=True),
    sa.Column('spread_range', sa.String(length=50), nullable=True),
    sa.Column('sun_exposure', sa.String(length=50), nullable=True),
    sa.Column('water_needs', sa.String(length=50), nullable=True),
    sa.Column('soil_type', sa.String(length=100), nullable=True),
    sa.Column('bloom_season', sa.String(length=100), nullable=True),
    sa.Column('bloom_color', sa.String(length=100), nullable=True),
    sa.Column('wildlife_value', sa.String(length=200), nullable=True),
    sa.Column('drought_tolerant', sa.Boolean(), nullable=True),
    sa.Column('deer_resistant', sa.Boolean(), nullable=True),
    sa.Column('care_instructions', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('in_my_yard', sa.Boolean(), nullable=True),
    sa.Column('date_planted', sa.Date(), nullable=True),
    sa.Column('location_in_yard', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plants_common_name'), ['common_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_plants_scientific_name'), ['scientific_name'], unique=False)

    op.create_table('care_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('care_logs')
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plants_scientific_name'))
        batch_op.drop_index(batch_op.f('ix_plants_common_name'))

    op.drop_table('plants')
    op.drop_table('plant_resources')
    # ### end Alembic commands ###
