"""Add SOTY tournament models

Revision ID: 75e96c5a6026
Revises: 635abf4f1200
Create Date: 2025-12-18 21:01:09.043521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75e96c5a6026'
down_revision = '635abf4f1200'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('soty_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.Integer(), nullable=True),
    sa.Column('end_date', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('soty_songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spotify_track_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('artist', sa.String(length=200), nullable=False),
    sa.Column('album', sa.String(length=200), nullable=True),
    sa.Column('release_date', sa.String(length=20), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('seed_number', sa.Integer(), nullable=True),
    sa.Column('artwork_url', sa.String(length=500), nullable=True),
    sa.Column('is_alive', sa.Boolean(), nullable=True),
    sa.Column('max_round_reached', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('soty_songs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_soty_songs_spotify_track_id'), ['spotify_track_id'], unique=True)

    op.create_table('soty_matchups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('position_in_round', sa.Integer(), nullable=False),
    sa.Column('song1_id', sa.Integer(), nullable=True),
    sa.Column('song2_id', sa.Integer(), nullable=True),
    sa.Column('winner_song_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['soty_rounds.id'], ),
    sa.ForeignKeyConstraint(['song1_id'], ['soty_songs.id'], ),
    sa.ForeignKeyConstraint(['song2_id'], ['soty_songs.id'], ),
    sa.ForeignKeyConstraint(['winner_song_id'], ['soty_songs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('soty_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('matchup_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('is_vote_changed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['matchup_id'], ['soty_matchups.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['soty_songs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'matchup_id', name='unique_user_matchup_vote')
    )
    with op.batch_alter_table('soty_votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_soty_votes_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('soty_votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_soty_votes_user_id'))

    op.drop_table('soty_votes')
    op.drop_table('soty_matchups')
    with op.batch_alter_table('soty_songs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_soty_songs_spotify_track_id'))

    op.drop_table('soty_songs')
    op.drop_table('soty_rounds')
    # ### end Alembic commands ###
