"""add columns

Revision ID: fd11a1d8f07f
Revises: 2891de635c8f
Create Date: 2025-12-20 23:09:36.997057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd11a1d8f07f'
down_revision = '2891de635c8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('soty_songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submitter_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('apple_music_id', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_soty_songs_apple_music_id'), ['apple_music_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_soty_songs_submitter_id'), ['submitter_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('soty_songs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_soty_songs_submitter_id'))
        batch_op.drop_index(batch_op.f('ix_soty_songs_apple_music_id'))
        batch_op.drop_column('apple_music_id')
        batch_op.drop_column('submitter_id')

    # ### end Alembic commands ###
